import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import InstallAppButton from "./pwa/install";
import AppSetup from "./appSetup";
import "@radix-ui/themes/styles.css";


const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
	applicationName: "Quiz Money",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<link rel="manifest" href="/manifest.json" />
				<link rel="icon" href="/favicon.ico" />
				<meta name="apple-mobile-web-app-title" content="Quiz Money" />
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1.0, maximum-scale=1.0"></meta>
			</head>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<AppSetup>{children}</AppSetup>
				<InstallAppButton />
			</body>
		</html>
	);
}
